all:
  children:
    nextcloud_servers:
      hosts:
        server1:
          ansible_host: "{{ server_ip }}"
          # Inicialmente nos conectamos como root
          # Una vez que el rol 'system' termine, podrías necesitar cambiar 'ansible_user' a usuario asignado en 'group_vars/all.yml' para futuras ejecuciones.
          ansible_user: "{{ new_user }}"
          ansible_ssh_private_key_file: "./ssh_keys/{{ new_user }}_ed25519"
          # Descomenta la siguiente línea y pon tu contraseña si te conectas por contraseña
          # ansible_password: "[PASSWORD]"
