---

- name: Instalar git si no está presente
  apt:
    name: git
    state: present

- name: Clonar repositorio oficial de cadviewer-conversion-server
  git:
    repo: https://github.com/CADViewer/cadviewer-conversion-server.git
    dest: /opt/autoxchange
    update: yes
    force: yes

- name: Copiar docker-compose.yml de AutoXchange
  template:
    src: docker-compose.yml.j2
    dest: /opt/autoxchange/docker-compose.yml

- name: Levantar stack de AutoXchange con Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/autoxchange
    state: present
    pull: always
